-- =====================================================================
-- SSOL Wellness House — migration: 실천방법 설명 문체를 하십시오체(~합니다)로 통일
-- (Supabase SQL Editor에 전체를 붙여넣고 Run)
--
-- 2026-09-25 owner 요청: wellness_practices.detail 375개가 전부 해라체("~한다.")로
-- 쓰여 있어 "설명하는 투"로 바꿔달라는 피드백 반영. title/category/domain/tier는 건드리지
-- 않고 detail 문장의 끝맺음만 하십시오체("~합니다.")로 바꾼다(뜻은 그대로, 어미만 변경).
-- 375개 전부 규칙 기반(해라체 종결어미 -> 하십시오체 종결어미)으로 기계적으로 변환했고,
-- 예외 처리가 필요했던 항목은 없었다(scripts 폴더에 변환 스크립트를 남기지 않고, 결과만
-- 이 마이그레이션에 담았다 — 필요하면 owner에게 원본 대조본을 별도로 제공 가능).
--
-- 추가로 COUPLE-BODY-L1-04(제목 "함께 요리해보기")는 특정 상대를 전제한 문구라 홈 화면
-- 일일 제안에 뜰 때 "누구랑 요리하라는 건지 불명확하다"는 피드백을 받아 제목/설명도 함께 바꾼다.
-- 여러 번 실행해도 안전하다(멱등 — 같은 값으로 다시 덮어쓸 뿐).
-- =====================================================================

begin;

update public.wellness_practices set title = '가볍게 요리해보기' where id = 'COUPLE-BODY-L1-04';

update public.wellness_practices set detail = '집 앞을 10~15분만 걸어도 기분 전환에 도움이 됩니다.' where id = 'SELF-BODY-L1-01';
update public.wellness_practices set detail = '좋아하는 곡 한 곡 길이만큼 몸을 가볍게 늘여줍니다.' where id = 'SELF-BODY-L1-02';
update public.wellness_practices set detail = '엘리베이터 대신 계단을 이용해 몸에 작은 자극을 줍니다.' where id = 'SELF-BODY-L1-03';
update public.wellness_practices set detail = '창문 밖이나 베란다에서 잠깐 햇볕을 쬡니다.' where id = 'SELF-BODY-L1-04';
update public.wellness_practices set detail = '몸을 깨우는 가장 짧고 쉬운 시작점입니다.' where id = 'SELF-BODY-L1-05';
update public.wellness_practices set detail = '10~15분에서 시작해 점차 시간을 늘려갑니다.' where id = 'SELF-BODY-L2-01';
update public.wellness_practices set detail = '부담 없는 거리부터 뛰어보며 체력을 확인합니다.' where id = 'SELF-BODY-L2-02';
update public.wellness_practices set detail = '이동 시간에 자연스럽게 운동량을 끼워 넣습니다.' where id = 'SELF-BODY-L2-03';
update public.wellness_practices set detail = '등산, 자전거 등 야외 활동을 정기 일정으로 만듭니다.' where id = 'SELF-BODY-L2-04';
update public.wellness_practices set detail = '작은 성취를 눈으로 확인하며 동기를 유지합니다.' where id = 'SELF-BODY-L2-05';
update public.wellness_practices set detail = '강도보다 꾸준함을 우선해 30~45분까지 늘려갑니다.' where id = 'SELF-BODY-L3-01';
update public.wellness_practices set detail = '댄스, 클라이밍 등 즐거운 활동을 정체성의 일부로 삼습니다.' where id = 'SELF-BODY-L3-02';
update public.wellness_practices set detail = '함께할 사람이 있으면 습관이 오래 유지됩니다.' where id = 'SELF-BODY-L3-03';
update public.wellness_practices set detail = '봄엔 걷기, 여름엔 수영처럼 장기 루틴을 설계합니다.' where id = 'SELF-BODY-L3-04';
update public.wellness_practices set detail = '무리한 목표 대신 지속 가능한 강도를 찾아갑니다.' where id = 'SELF-BODY-L3-05';
update public.wellness_practices set detail = '잠들기 전 하루 중 좋았던 순간 하나를 떠올립니다.' where id = 'SELF-MIND-L1-01';
update public.wellness_practices set detail = '"난 안 돼" 같은 말이 떠오르면 잠시 멈춰 인식합니다.' where id = 'SELF-MIND-L1-02';
update public.wellness_practices set detail = '보이는 것 5개, 만져지는 것 4개 순으로 주의를 현재로 돌립니다.' where id = 'SELF-MIND-L1-03';
update public.wellness_practices set detail = '지금 느끼는 감정을 한 단어로 표현해봅니다.' where id = 'SELF-MIND-L1-04';
update public.wellness_practices set detail = '숨을 천천히 들이쉬고 내쉬며 생각의 속도를 늦춥니다.' where id = 'SELF-MIND-L1-05';
update public.wellness_practices set detail = '감사한 일 3가지를 짧게 적으며 하루를 마무리합니다.' where id = 'SELF-MIND-L2-01';
update public.wellness_practices set detail = '속상한 상황도 배움의 기회로 바꿔 생각해봅니다.' where id = 'SELF-MIND-L2-02';
update public.wellness_practices set detail = '나에게 한 말을 친한 친구에게 하듯 부드럽게 바꿔 적습니다.' where id = 'SELF-MIND-L2-03';
update public.wellness_practices set detail = '일주일간 감정 기복이 언제 생기는지 짧게 메모합니다.' where id = 'SELF-MIND-L2-04';
update public.wellness_practices set detail = '판단 없이 지금 이 순간에 집중하는 연습을 반복합니다.' where id = 'SELF-MIND-L2-05';
update public.wellness_practices set detail = '잘하는 것과 좋아하는 것을 적어두고 월 1회 다시 읽습니다.' where id = 'SELF-MIND-L3-01';
update public.wellness_practices set detail = '실패를 "아직 안 된 것"으로 재해석하는 연습을 반복합니다.' where id = 'SELF-MIND-L3-02';
update public.wellness_practices set detail = '힘든 순간마다 스스로를 다그치기보다 다독이는 습관을 들입니다.' where id = 'SELF-MIND-L3-03';
update public.wellness_practices set detail = '중요하게 여기는 가치를 정리해 선택의 나침반으로 씁니다.' where id = 'SELF-MIND-L3-04';
update public.wellness_practices set detail = '한 달에 한 번 무엇이 나아졌는지 스스로 점검합니다.' where id = 'SELF-MIND-L3-05';
update public.wellness_practices set detail = '"오늘 좀 지쳤어"처럼 짧게라도 감정을 말로 꺼내봅니다.' where id = 'SELF-TALK-L1-01';
update public.wellness_practices set detail = '가벼운 연락으로 관계의 끈을 이어둡니다.' where id = 'SELF-TALK-L1-02';
update public.wellness_practices set detail = '작은 감사 표현이 관계와 기분 모두를 데웁니다.' where id = 'SELF-TALK-L1-03';
update public.wellness_practices set detail = '말하기 전에 먼저 글로 정리해보면 감정이 선명해집니다.' where id = 'SELF-TALK-L1-04';
update public.wellness_practices set detail = '동료나 가족과 짧은 대화로 하루를 부드럽게 엽니다.' where id = 'SELF-TALK-L1-05';
update public.wellness_practices set detail = '에너지를 주는 관계에 의식적으로 시간을 더 씁니다.' where id = 'SELF-TALK-L2-01';
update public.wellness_practices set detail = '가벼운 안부를 넘어 속마음을 나누는 자리를 정기적으로 만듭니다.' where id = 'SELF-TALK-L2-02';
update public.wellness_practices set detail = '"너는~" 대신 "나는 ~하게 느껴"로 말하는 연습을 합니다.' where id = 'SELF-TALK-L2-03';
update public.wellness_practices set detail = '매번 새로 찾기보다 믿을 만한 한 사람을 정해둡니다.' where id = 'SELF-TALK-L2-04';
update public.wellness_practices set detail = '얕은 연결보다 깊은 연결에 시간을 씁니다.' where id = 'SELF-TALK-L2-05';
update public.wellness_practices set detail = '에너지를 소모시키는 관계에 대한 노출을 서서히 줄입니다.' where id = 'SELF-TALK-L3-01';
update public.wellness_practices set detail = '관심사가 맞는 새로운 사람들과의 접점을 늘려갑니다.' where id = 'SELF-TALK-L3-02';
update public.wellness_practices set detail = '동호회, 스터디 등 꾸준히 만나는 공동체를 만듭니다.' where id = 'SELF-TALK-L3-03';
update public.wellness_practices set detail = '반복되는 대화 방식의 문제를 스스로 파악해갑니다.' where id = 'SELF-TALK-L3-04';
update public.wellness_practices set detail = '분기별로 지금의 관계들이 나에게 맞는지 되돌아봅니다.' where id = 'SELF-TALK-L3-05';
update public.wellness_practices set detail = '나를 위한 작은 선물로 기분을 환기합니다.' where id = 'SELF-CARE-L1-01';
update public.wellness_practices set detail = '잠깐 눈을 감고 호흡에만 집중하는 시간을 갖습니다.' where id = 'SELF-CARE-L1-02';
update public.wellness_practices set detail = '좋아하는 향초나 디퓨저로 잠깐의 휴식감을 만듭니다.' where id = 'SELF-CARE-L1-03';
update public.wellness_practices set detail = '10~15분만이라도 방해받지 않는 시간을 확보합니다.' where id = 'SELF-CARE-L1-04';
update public.wellness_practices set detail = '서두르지 않고 음료를 음미하며 잠시 멈춥니다.' where id = 'SELF-CARE-L1-05';
update public.wellness_practices set detail = '취미, 반신욕 등 나만을 위한 시간을 정기적으로 냅니다.' where id = 'SELF-CARE-L2-01';
update public.wellness_practices set detail = '매일 비슷한 시간에 자고 일어나는 리듬을 만듭니다.' where id = 'SELF-CARE-L2-02';
update public.wellness_practices set detail = '아무 일정도 넣지 않는 날을 의식적으로 비워둡니다.' where id = 'SELF-CARE-L2-03';
update public.wellness_practices set detail = '바쁘더라도 규칙적인 식사로 에너지 기반을 다집니다.' where id = 'SELF-CARE-L2-04';
update public.wellness_practices set detail = '부담 없는 선에서 나를 기쁘게 하는 것들을 정해둡니다.' where id = 'SELF-CARE-L2-05';
update public.wellness_practices set detail = '세 가지 기본 축을 꾸준히 관리하는 습관을 만듭니다.' where id = 'SELF-CARE-L3-01';
update public.wellness_practices set detail = '짧은 여행이나 방학 같은 재충전 기간을 미리 계획합니다.' where id = 'SELF-CARE-L3-02';
update public.wellness_practices set detail = '해야 할 일 목록에 나를 돌보는 일도 함께 적습니다.' where id = 'SELF-CARE-L3-03';
update public.wellness_practices set detail = '상황별로 무엇이 나를 회복시키는지 정리해둡니다.' where id = 'SELF-CARE-L3-04';
update public.wellness_practices set detail = '무리한 요청에는 정중히 거절하는 것을 기본값으로 삼습니다.' where id = 'SELF-CARE-L3-05';
update public.wellness_practices set detail = '가벼운 콘텐츠로 나에 대한 이해를 넓혀봅니다.' where id = 'SELF-HELP-L1-01';
update public.wellness_practices set detail = '가벼운 자가진단으로 지금 상태를 점검해봅니다.' where id = 'SELF-HELP-L1-02';
update public.wellness_practices set detail = '혼자 끌어안지 않고 존재를 알리는 것부터 시작합니다.' where id = 'SELF-HELP-L1-03';
update public.wellness_practices set detail = '믿을 수 있는 전문가·기관의 콘텐츠를 구독해둡니다.' where id = 'SELF-HELP-L1-04';
update public.wellness_practices set detail = '누군가에게 말하기 전, 글로 상태를 정리해봅니다.' where id = 'SELF-HELP-L1-05';
update public.wellness_practices set detail = '정기적인 대화 상대를 정해 마음을 자주 나눕니다.' where id = 'SELF-HELP-L2-01';
update public.wellness_practices set detail = '비슷한 고민을 가진 사람들과 경험을 나눠봅니다.' where id = 'SELF-HELP-L2-02';
update public.wellness_practices set detail = '체계적인 자료를 통해 단계적으로 나를 탐색합니다.' where id = 'SELF-HELP-L2-03';
update public.wellness_practices set detail = '도움을 청하는 것도 능력이라는 관점을 연습합니다.' where id = 'SELF-HELP-L2-04';
update public.wellness_practices set detail = '스스로에게 "요즘 어때?"를 자주 물어봅니다.' where id = 'SELF-HELP-L2-05';
update public.wellness_practices set detail = '필요하다고 느껴질 때 전문가의 도움을 받아봅니다.' where id = 'SELF-HELP-L3-01';
update public.wellness_practices set detail = '지속되는 어려움이라면 전문기관 상담을 고려해봅니다.' where id = 'SELF-HELP-L3-02';
update public.wellness_practices set detail = '한 번에 해결되는 문제가 아님을 받아들이고 꾸준히 나아갑니다.' where id = 'SELF-HELP-L3-03';
update public.wellness_practices set detail = '혼자 해결해야 한다는 부담을 내려놓는 관점을 키웁니다.' where id = 'SELF-HELP-L3-04';
update public.wellness_practices set detail = '여러 층의 도움 자원을 미리 마련해둡니다.' where id = 'SELF-HELP-L3-05';
update public.wellness_practices set detail = '짧은 메시지 한 통으로 연결을 확인합니다.' where id = 'REL-BODY-L1-01';
update public.wellness_practices set detail = '작은 인사가 관계의 첫걸음이 됩니다.' where id = 'REL-BODY-L1-02';
update public.wellness_practices set detail = '간단한 호의로 친밀감을 표현합니다.' where id = 'REL-BODY-L1-03';
update public.wellness_practices set detail = '대화가 어렵다면 나란히 걷는 것부터 시작합니다.' where id = 'REL-BODY-L1-04';
update public.wellness_practices set detail = '댓글이나 좋아요로 작은 관심을 표현합니다.' where id = 'REL-BODY-L1-05';
update public.wellness_practices set detail = '정기적으로 몸을 움직이며 만나는 자리를 만듭니다.' where id = 'REL-BODY-L2-01';
update public.wellness_practices set detail = '즉흥이 아닌 정해진 만남으로 관계를 이어갑니다.' where id = 'REL-BODY-L2-02';
update public.wellness_practices set detail = '공동의 목표는 관계를 자연스럽게 이어줍니다.' where id = 'REL-BODY-L2-03';
update public.wellness_practices set detail = '꾸준히 참석하는 것만으로도 관계가 다져집니다.' where id = 'REL-BODY-L2-04';
update public.wellness_practices set detail = '상대가 좋아하는 활동을 함께 해봅니다.' where id = 'REL-BODY-L2-05';
update public.wellness_practices set detail = '같은 사람들과 반복해서 만나는 자리를 만듭니다.' where id = 'REL-BODY-L3-01';
update public.wellness_practices set detail = '매년 함께하는 이벤트로 관계에 지속성을 부여합니다.' where id = 'REL-BODY-L3-02';
update public.wellness_practices set detail = '잊지 않고 연락하는 나만의 주기를 정해둡니다.' where id = 'REL-BODY-L3-03';
update public.wellness_practices set detail = '관계망을 넓히는 활동을 습관처럼 이어갑니다.' where id = 'REL-BODY-L3-04';
update public.wellness_practices set detail = '바쁘더라도 사람 만나는 시간을 우선순위에 둡니다.' where id = 'REL-BODY-L3-05';
update public.wellness_practices set detail = '판단하기 전에 상대의 맥락을 떠올려봅니다.' where id = 'REL-MIND-L1-01';
update public.wellness_practices set detail = '확신하기 전에 다른 가능성을 생각해봅니다.' where id = 'REL-MIND-L1-02';
update public.wellness_practices set detail = '부정적 감정이 클 때일수록 의식적으로 시도합니다.' where id = 'REL-MIND-L1-03';
update public.wellness_practices set detail = '감정이 앞섰는지 스스로에게 물어봅니다.' where id = 'REL-MIND-L1-04';
update public.wellness_practices set detail = '관계의 여유를 만드는 짧은 리프레이밍입니다.' where id = 'REL-MIND-L1-05';
update public.wellness_practices set detail = '비슷한 갈등이 왜 반복되는지 메모하며 살펴봅니다.' where id = 'REL-MIND-L2-01';
update public.wellness_practices set detail = '내가 상대에게 바라는 것이 합리적인지 돌아봅니다.' where id = 'REL-MIND-L2-02';
update public.wellness_practices set detail = '무엇을 우선시하는지 알면 관계 선택이 쉬워집니다.' where id = 'REL-MIND-L2-03';
update public.wellness_practices set detail = '타인과 나를 비교하는 습관을 의식적으로 줄입니다.' where id = 'REL-MIND-L2-04';
update public.wellness_practices set detail = '즉각 반응하기보다 하루 정도 생각을 묵혀봅니다.' where id = 'REL-MIND-L2-05';
update public.wellness_practices set detail = '충돌을 관계를 더 깊게 만드는 계기로 재해석합니다.' where id = 'REL-MIND-L3-01';
update public.wellness_practices set detail = '나에게 맞는 좋은 관계의 모습을 구체화해갑니다.' where id = 'REL-MIND-L3-02';
update public.wellness_practices set detail = '관계 속에서도 자기중심을 지키는 연습을 이어갑니다.' where id = 'REL-MIND-L3-03';
update public.wellness_practices set detail = '지나간 관계에서도 배움을 찾아 다음에 적용합니다.' where id = 'REL-MIND-L3-04';
update public.wellness_practices set detail = '이해하되 나를 잃지 않는 태도를 장기적으로 훈련합니다.' where id = 'REL-MIND-L3-05';
update public.wellness_practices set detail = '구체적인 한 가지를 짚어 칭찬해봅니다.' where id = 'REL-TALK-L1-01';
update public.wellness_practices set detail = '비난 대신 내 감정을 주어로 말해봅니다.' where id = 'REL-TALK-L1-02';
update public.wellness_practices set detail = '질문 하나가 대화의 문을 엽니다.' where id = 'REL-TALK-L1-03';
update public.wellness_practices set detail = '쌓아두지 않고 가볍게라도 표현해봅니다.' where id = 'REL-TALK-L1-04';
update public.wellness_practices set detail = '"그러니까 ~라는 거지?"로 이해를 확인합니다.' where id = 'REL-TALK-L1-05';
update public.wellness_practices set detail = '말을 끊지 않고 끝까지 들어주는 연습을 반복합니다.' where id = 'REL-TALK-L2-01';
update public.wellness_practices set detail = '형식적인 인사를 넘어 근황을 진짜로 물어봅니다.' where id = 'REL-TALK-L2-02';
update public.wellness_practices set detail = '묵히지 않고 빠른 시일 내 대화를 시도합니다.' where id = 'REL-TALK-L2-03';
update public.wellness_practices set detail = '관계를 깊게 만드는 질문을 습관화합니다.' where id = 'REL-TALK-L2-04';
update public.wellness_practices set detail = '"고마워"에 이유를 덧붙여 진심을 전합니다.' where id = 'REL-TALK-L2-05';
update public.wellness_practices set detail = '정중하지만 분명하게 거절하는 표현을 연습해둡니다.' where id = 'REL-TALK-L3-01';
update public.wellness_practices set detail = '표면적 대화를 넘어 가치관을 나누는 대화를 늘립니다.' where id = 'REL-TALK-L3-02';
update public.wellness_practices set detail = '감정적 대응 대신 일관된 소통 방식을 갖춥니다.' where id = 'REL-TALK-L3-03';
update public.wellness_practices set detail = '솔직하되 상처 주지 않는 표현법을 다듬어갑니다.' where id = 'REL-TALK-L3-04';
update public.wellness_practices set detail = '가까운 사이와 공적인 사이의 화법을 구분해 씁니다.' where id = 'REL-TALK-L3-05';
update public.wellness_practices set detail = '약속 사이 짧은 휴식으로 에너지를 회복합니다.' where id = 'REL-CARE-L1-01';
update public.wellness_practices set detail = '즉각 반응해야 한다는 압박을 내려놓습니다.' where id = 'REL-CARE-L1-02';
update public.wellness_practices set detail = '모든 초대에 응할 필요는 없다는 것을 연습합니다.' where id = 'REL-CARE-L1-03';
update public.wellness_practices set detail = '사람을 만나지 않는 저녁을 의도적으로 만듭니다.' where id = 'REL-CARE-L1-04';
update public.wellness_practices set detail = '사람을 만나기 전 내 컨디션부터 살핍니다.' where id = 'REL-CARE-L1-05';
update public.wellness_practices set detail = '만남의 빈도나 시간을 조금씩 조정해봅니다.' where id = 'REL-CARE-L2-01';
update public.wellness_practices set detail = '관계와 별개로 나를 채우는 활동을 이어갑니다.' where id = 'REL-CARE-L2-02';
update public.wellness_practices set detail = '지금의 인간관계가 버거운지 스스로 체크합니다.' where id = 'REL-CARE-L2-03';
update public.wellness_practices set detail = '비교와 피로를 주는 소비 습관을 조정해봅니다.' where id = 'REL-CARE-L2-04';
update public.wellness_practices set detail = '매주 두 가지 시간을 의식적으로 배분합니다.' where id = 'REL-CARE-L2-05';
update public.wellness_practices set detail = '넓고 얕은 관계와 좁고 깊은 관계 중 나의 성향을 인정합니다.' where id = 'REL-CARE-L3-01';
update public.wellness_practices set detail = '언제 관계를 정리할지에 대한 나만의 원칙을 갖습니다.' where id = 'REL-CARE-L3-02';
update public.wellness_practices set detail = '관계에 흡수되지 않는 독립적인 나를 유지합니다.' where id = 'REL-CARE-L3-03';
update public.wellness_practices set detail = '주기적으로 관계를 정리하고 재정비하는 시간을 갖습니다.' where id = 'REL-CARE-L3-04';
update public.wellness_practices set detail = '반복되는 소모적 관계 패턴 자체를 바꿔나갑니다.' where id = 'REL-CARE-L3-05';
update public.wellness_practices set detail = '혼자 안고 있지 않고 가볍게 이야기부터 꺼냅니다.' where id = 'REL-HELP-L1-01';
update public.wellness_practices set detail = '온라인 커뮤니티 등에서 공감대를 찾아봅니다.' where id = 'REL-HELP-L1-02';
update public.wellness_practices set detail = '책이나 영상으로 다른 사람들의 사례를 참고합니다.' where id = 'REL-HELP-L1-03';
update public.wellness_practices set detail = '당사자가 아닌 사람에게 객관적 의견을 구해봅니다.' where id = 'REL-HELP-L1-04';
update public.wellness_practices set detail = '말하기 전에 상황을 글로 정리해봅니다.' where id = 'REL-HELP-L1-05';
update public.wellness_practices set detail = '대화법, 관계 맺기에 관한 자료를 꾸준히 찾아봅니다.' where id = 'REL-HELP-L2-01';
update public.wellness_practices set detail = '경험이 많은 사람의 시각을 정기적으로 들어봅니다.' where id = 'REL-HELP-L2-02';
update public.wellness_practices set detail = '비슷한 상황의 사람들과 꾸준히 교류합니다.' where id = 'REL-HELP-L2-03';
update public.wellness_practices set detail = '믿을 사람에게 반복되는 상황을 구체적으로 나눕니다.' where id = 'REL-HELP-L2-04';
update public.wellness_practices set detail = '관계 문제는 혼자 풀기 어렵다는 것을 받아들입니다.' where id = 'REL-HELP-L2-05';
update public.wellness_practices set detail = '패턴이 반복된다면 전문가의 시각을 빌려봅니다.' where id = 'REL-HELP-L3-01';
update public.wellness_practices set detail = '완성이 아니라 계속 배워가는 기술로 받아들입니다.' where id = 'REL-HELP-L3-02';
update public.wellness_practices set detail = '관련 자료나 상담을 통해 근본 패턴을 파악해갑니다.' where id = 'REL-HELP-L3-03';
update public.wellness_practices set detail = '여러 사람에게 나눠 기댈 수 있는 관계망을 만듭니다.' where id = 'REL-HELP-L3-04';
update public.wellness_practices set detail = '인간관계에서 얻은 통찰을 일, 가족에도 연결합니다.' where id = 'REL-HELP-L3-05';
update public.wellness_practices set detail = '말없이 나란히 걷는 것만으로도 연결감이 생깁니다.' where id = 'COUPLE-BODY-L1-01';
update public.wellness_practices set detail = '작은 스킨십이 정서적 유대를 강화합니다.' where id = 'COUPLE-BODY-L1-02';
update public.wellness_practices set detail = '짧은 스킨십보다 조금 더 오래 안아봅니다.' where id = 'COUPLE-BODY-L1-03';
update public.wellness_practices set detail = '재료 손질부터 플레이팅까지 몸을 움직이며 자연스럽게 기분을 환기합니다.' where id = 'COUPLE-BODY-L1-04';
update public.wellness_practices set detail = '거창한 계획 없이도 함께 걷는 시간을 만듭니다.' where id = 'COUPLE-BODY-L1-05';
update public.wellness_practices set detail = '주 1회 등 정해진 시간에 둘만의 시간을 확보합니다.' where id = 'COUPLE-BODY-L2-01';
update public.wellness_practices set detail = '같은 운동을 함께 하며 몸과 관계를 동시에 챙깁니다.' where id = 'COUPLE-BODY-L2-02';
update public.wellness_practices set detail = '서로 새로운 곳을 소개하며 신선함을 유지합니다.' where id = 'COUPLE-BODY-L2-03';
update public.wellness_practices set detail = '바쁠수록 잊기 쉬운 스킨십을 챙깁니다.' where id = 'COUPLE-BODY-L2-04';
update public.wellness_practices set detail = '일정 속에 둘만의 시간을 고정해둡니다.' where id = 'COUPLE-BODY-L2-05';
update public.wellness_practices set detail = '운동, 여행 등 함께 성장하는 활동을 갖습니다.' where id = 'COUPLE-BODY-L3-01';
update public.wellness_practices set detail = '일상에서 벗어나는 시간을 함께 계획합니다.' where id = 'COUPLE-BODY-L3-02';
update public.wellness_practices set detail = '관계의 의미 있는 날들을 함께 기억하고 축하합니다.' where id = 'COUPLE-BODY-L3-03';
update public.wellness_practices set detail = '저축, 건강 등 함께 이루는 목표를 정합니다.' where id = 'COUPLE-BODY-L3-04';
update public.wellness_practices set detail = '바쁜 시기에도 흔들리지 않는 루틴을 만듭니다.' where id = 'COUPLE-BODY-L3-05';
update public.wellness_practices set detail = '다투기 전 잠깐 멈춰 상대의 장점을 생각해봅니다.' where id = 'COUPLE-MIND-L1-01';
update public.wellness_practices set detail = '당연하게 여겼던 노력을 의식적으로 알아챕니다.' where id = 'COUPLE-MIND-L1-02';
update public.wellness_practices set detail = '감정을 쏟아내기 전에 원인을 먼저 파악합니다.' where id = 'COUPLE-MIND-L1-03';
update public.wellness_practices set detail = '바쁜 하루를 보냈을 상대의 입장을 헤아려봅니다.' where id = 'COUPLE-MIND-L1-04';
update public.wellness_practices set detail = '누가 옳은지보다 무엇이 우리에게 좋은지를 생각합니다.' where id = 'COUPLE-MIND-L1-05';
update public.wellness_practices set detail = '취향, 걱정거리 등을 묻는 질문을 정기적으로 나눕니다.' where id = 'COUPLE-MIND-L2-01';
update public.wellness_practices set detail = '반복되는 다툼의 원인을 둘이 함께 짚어봅니다.' where id = 'COUPLE-MIND-L2-02';
update public.wellness_practices set detail = '상대가 사랑을 느끼는 방식을 관찰하고 맞춰갑니다.' where id = 'COUPLE-MIND-L2-03';
update public.wellness_practices set detail = '좋았던 순간들을 의식적으로 되새깁니다.' where id = 'COUPLE-MIND-L2-04';
update public.wellness_practices set detail = '막연한 서운함 대신 원하는 바를 명확히 합니다.' where id = 'COUPLE-MIND-L2-05';
update public.wellness_practices set detail = '서로를 적이 아닌 한 팀으로 보는 시각을 굳혀갑니다.' where id = 'COUPLE-MIND-L3-01';
update public.wellness_practices set detail = '앞으로 함께 만들어갈 삶의 모습을 주기적으로 이야기합니다.' where id = 'COUPLE-MIND-L3-02';
update public.wellness_practices set detail = '같아지길 바라기보다 다름을 존중하는 법을 배웁니다.' where id = 'COUPLE-MIND-L3-03';
update public.wellness_practices set detail = '당연함이 아닌 고마움을 표현하는 문화를 정착시킵니다.' where id = 'COUPLE-MIND-L3-04';
update public.wellness_practices set detail = '왜 이 사람과 함께하는지 주기적으로 돌아봅니다.' where id = 'COUPLE-MIND-L3-05';
update public.wellness_practices set detail = '"왜 안 했어" 대신 "나는 이럴 때 서운했어"로 시작합니다.' where id = 'COUPLE-TALK-L1-01';
update public.wellness_practices set detail = '하루 5분이라도 서로의 일과를 공유합니다.' where id = 'COUPLE-TALK-L1-02';
update public.wellness_practices set detail = '구체적인 행동을 짚어 감사를 표현합니다.' where id = 'COUPLE-TALK-L1-03';
update public.wellness_practices set detail = '쌓아두지 않고 가볍게라도 그때그때 말합니다.' where id = 'COUPLE-TALK-L1-04';
update public.wellness_practices set detail = '듣고 있다는 걸 적극적으로 표현해줍니다.' where id = 'COUPLE-TALK-L1-05';
update public.wellness_practices set detail = '정해진 시간에 깊이 있는 대화를 나눕니다.' where id = 'COUPLE-TALK-L2-01';
update public.wellness_practices set detail = '감정이 격해지면 잠깐 멈췄다 다시 이야기하기로 약속합니다.' where id = 'COUPLE-TALK-L2-02';
update public.wellness_practices set detail = '관계가 편해질수록 오히려 더 자주 확인합니다.' where id = 'COUPLE-TALK-L2-03';
update public.wellness_practices set detail = '일상적인 순간에도 긍정적 표현을 자주 건넵니다.' where id = 'COUPLE-TALK-L2-04';
update public.wellness_practices set detail = '돈, 미래 등 불편한 주제를 미루지 않고 다룹니다.' where id = 'COUPLE-TALK-L2-05';
update public.wellness_practices set detail = '다툼 중에도 관계를 회복하려는 신호를 서로 알아챕니다.' where id = 'COUPLE-TALK-L3-01';
update public.wellness_practices set detail = '구조화된 자료로 소통 방식을 함께 점검해봅니다.' where id = 'COUPLE-TALK-L3-02';
update public.wellness_practices set detail = '작은 관심 요청에 의식적으로 반응해줍니다.' where id = 'COUPLE-TALK-L3-03';
update public.wellness_practices set detail = '다투는 방식에도 서로 합의된 원칙을 만듭니다.' where id = 'COUPLE-TALK-L3-04';
update public.wellness_practices set detail = '시간이 지나며 달라지는 서로에 맞춰 대화법도 조정합니다.' where id = 'COUPLE-TALK-L3-05';
update public.wellness_practices set detail = '바로 대응하기보다 잠시 숨을 고릅니다.' where id = 'COUPLE-CARE-L1-01';
update public.wellness_practices set detail = '관계 안에서도 나만의 순간을 확보합니다.' where id = 'COUPLE-CARE-L1-02';
update public.wellness_practices set detail = '상대를 살피기 전에 내 상태부터 점검합니다.' where id = 'COUPLE-CARE-L1-03';
update public.wellness_practices set detail = '솔직하게 컨디션을 알리고 쉬어갑니다.' where id = 'COUPLE-CARE-L1-04';
update public.wellness_practices set detail = '쌓아두지 않고 가볍게 해소합니다.' where id = 'COUPLE-CARE-L1-05';
update public.wellness_practices set detail = '연인/배우자 외의 나의 영역을 계속 지켜갑니다.' where id = 'COUPLE-CARE-L2-01';
update public.wellness_practices set detail = '관계에만 몰입하지 않고 다른 지지체계도 유지합니다.' where id = 'COUPLE-CARE-L2-02';
update public.wellness_practices set detail = '관계와 별개로 회복할 수 있는 나만의 방법을 갖습니다.' where id = 'COUPLE-CARE-L2-03';
update public.wellness_practices set detail = '함께하는 시간과 개인 시간을 균형 있게 배분합니다.' where id = 'COUPLE-CARE-L2-04';
update public.wellness_practices set detail = '다툰 뒤 스스로를 다독이는 방법을 마련해둡니다.' where id = 'COUPLE-CARE-L2-05';
update public.wellness_practices set detail = '장기적으로 지속 가능한 균형점을 찾아갑니다.' where id = 'COUPLE-CARE-L3-01';
update public.wellness_practices set detail = '관계 속에서도 지킬 나만의 원칙을 명확히 합니다.' where id = 'COUPLE-CARE-L3-02';
update public.wellness_practices set detail = '희생이 일방적이라면 변화를 시도할 힘을 기릅니다.' where id = 'COUPLE-CARE-L3-03';
update public.wellness_practices set detail = '관계뿐 아니라 개인으로서의 성장도 놓치지 않습니다.' where id = 'COUPLE-CARE-L3-04';
update public.wellness_practices set detail = '단기 노력이 아닌 오래 지속 가능한 방식을 만듭니다.' where id = 'COUPLE-CARE-L3-05';
update public.wellness_practices set detail = '부담 없는 콘텐츠로 대화의 소재를 만듭니다.' where id = 'COUPLE-HELP-L1-01';
update public.wellness_practices set detail = '혼자 고민하지 말고 주변의 시각을 들어봅니다.' where id = 'COUPLE-HELP-L1-02';
update public.wellness_practices set detail = '가벼운 테스트로 서로를 이해하는 계기를 만듭니다.' where id = 'COUPLE-HELP-L1-03';
update public.wellness_practices set detail = '말로 하기 어렵다면 글로 먼저 전해봅니다.' where id = 'COUPLE-HELP-L1-04';
update public.wellness_practices set detail = '비슷한 고민을 겪은 사례에서 힌트를 얻습니다.' where id = 'COUPLE-HELP-L1-05';
update public.wellness_practices set detail = '믿을 만한 사람의 시각을 주기적으로 들어봅니다.' where id = 'COUPLE-HELP-L2-01';
update public.wellness_practices set detail = '비슷한 상황의 사람들과 경험을 나눠봅니다.' where id = 'COUPLE-HELP-L2-02';
update public.wellness_practices set detail = '구조화된 자료로 단계적으로 관계를 점검합니다.' where id = 'COUPLE-HELP-L2-03';
update public.wellness_practices set detail = '전문적인 관점을 부담 없이 접해봅니다.' where id = 'COUPLE-HELP-L2-04';
update public.wellness_practices set detail = '쌓이기 전에 도움을 구하는 것을 자연스럽게 여깁니다.' where id = 'COUPLE-HELP-L2-05';
update public.wellness_practices set detail = '필요하다고 느껴질 때 전문가와 함께 관계를 점검해봅니다.' where id = 'COUPLE-HELP-L3-01';
update public.wellness_practices set detail = '문제 해결이 아닌 지속적인 성장으로 관계를 바라봅니다.' where id = 'COUPLE-HELP-L3-02';
update public.wellness_practices set detail = '일정 주기로 관계 상태를 함께 돌아보는 자리를 만듭니다.' where id = 'COUPLE-HELP-L3-03';
update public.wellness_practices set detail = '각자의 성장을 응원하는 관계로 발전시켜갑니다.' where id = 'COUPLE-HELP-L3-04';
update public.wellness_practices set detail = '관계의 어려움도 혼자 해결할 필요 없다는 것을 받아들입니다.' where id = 'COUPLE-HELP-L3-05';
update public.wellness_practices set detail = '식사 후 10분이라도 걸으며 머리를 식힙니다.' where id = 'WORK-BODY-L1-01';
update public.wellness_practices set detail = '목, 어깨 등 뭉친 부위를 짧게 풀어줍니다.' where id = 'WORK-BODY-L1-02';
update public.wellness_practices set detail = '장시간 앉아있는 습관을 짧게라도 끊어줍니다.' where id = 'WORK-BODY-L1-03';
update public.wellness_practices set detail = '이동할 때 엘리베이터 대신 계단을 선택합니다.' where id = 'WORK-BODY-L1-04';
update public.wellness_practices set detail = '짧은 움직임을 겸해 수분을 챙깁니다.' where id = 'WORK-BODY-L1-05';
update public.wellness_practices set detail = '50분 집중 후 10분 휴식처럼 리듬을 만듭니다.' where id = 'WORK-BODY-L2-01';
update public.wellness_practices set detail = '이동 시간에 자연스럽게 운동량을 확보합니다.' where id = 'WORK-BODY-L2-02';
update public.wellness_practices set detail = '점심시간이나 퇴근 후 짧은 운동을 정기화합니다.' where id = 'WORK-BODY-L2-03';
update public.wellness_practices set detail = '정돈된 공간이 집중력과 기분에 영향을 줍니다.' where id = 'WORK-BODY-L2-04';
update public.wellness_practices set detail = '장시간 앉아 일하는 환경을 개선합니다.' where id = 'WORK-BODY-L2-05';
update public.wellness_practices set detail = '퇴근 후 운동을 하루를 마무리하는 신호로 삼습니다.' where id = 'WORK-BODY-L3-01';
update public.wellness_practices set detail = '소진되기 전에 미리 휴식을 배치해둡니다.' where id = 'WORK-BODY-L3-02';
update public.wellness_practices set detail = '재택근무라도 업무 공간과 휴식 공간을 분리합니다.' where id = 'WORK-BODY-L3-03';
update public.wellness_practices set detail = '커리어를 오래 지속하기 위한 체력 기반을 다집니다.' where id = 'WORK-BODY-L3-04';
update public.wellness_practices set detail = '바쁜 시기와 쉬는 시기를 스스로 조절하는 힘을 기릅니다.' where id = 'WORK-BODY-L3-05';
update public.wellness_practices set detail = '완벽하지 않아도 해낸 것을 스스로 알아줍니다.' where id = 'WORK-MIND-L1-01';
update public.wellness_practices set detail = '작은 성취라도 눈에 보이게 기록합니다.' where id = 'WORK-MIND-L1-02';
update public.wellness_practices set detail = '실패를 즉시 자책하지 않고 관점을 바꿔봅니다.' where id = 'WORK-MIND-L1-03';
update public.wellness_practices set detail = '무엇이 힘든지 그때그때 기록해둡니다.' where id = 'WORK-MIND-L1-04';
update public.wellness_practices set detail = '모든 걸 다 하려는 부담을 줄입니다.' where id = 'WORK-MIND-L1-05';
update public.wellness_practices set detail = '언제 스트레스가 몰리는지 데이터를 쌓아봅니다.' where id = 'WORK-MIND-L2-01';
update public.wellness_practices set detail = '모든 일에 100%를 요구하지 않는 연습을 합니다.' where id = 'WORK-MIND-L2-02';
update public.wellness_practices set detail = '이 일이 나에게 어떤 의미인지 주기적으로 확인합니다.' where id = 'WORK-MIND-L2-03';
update public.wellness_practices set detail = '동료나 남들과의 비교에서 오는 스트레스를 의식적으로 줄입니다.' where id = 'WORK-MIND-L2-04';
update public.wellness_practices set detail = '중요한 일과 급한 일을 구분하는 연습을 반복합니다.' where id = 'WORK-MIND-L2-05';
update public.wellness_practices set detail = '지침, 무기력 등 초기 신호를 놓치지 않고 살핍니다.' where id = 'WORK-MIND-L3-01';
update public.wellness_practices set detail = '커리어의 방향성을 스스로 납득할 수 있게 정리합니다.' where id = 'WORK-MIND-L3-02';
update public.wellness_practices set detail = '당장의 어려움을 긴 여정의 한 지점으로 재구성합니다.' where id = 'WORK-MIND-L3-03';
update public.wellness_practices set detail = '일의 결과가 나의 전부가 아니라는 관점을 키웁니다.' where id = 'WORK-MIND-L3-04';
update public.wellness_practices set detail = '타인의 기준이 아닌 나만의 성장 기준을 세웁니다.' where id = 'WORK-MIND-L3-05';
update public.wellness_practices set detail = '혼자 끌어안지 않고 가볍게라도 나눠봅니다.' where id = 'WORK-TALK-L1-01';
update public.wellness_practices set detail = '모르는 것을 인정하고 도움을 청해봅니다.' where id = 'WORK-TALK-L1-02';
update public.wellness_practices set detail = '작은 인정의 말이 관계와 분위기를 데웁니다.' where id = 'WORK-TALK-L1-03';
update public.wellness_practices set detail = '회의 중 작은 의견부터 말하는 연습을 합니다.' where id = 'WORK-TALK-L1-04';
update public.wellness_practices set detail = '업무 외 대화로 관계의 여유를 만듭니다.' where id = 'WORK-TALK-L1-05';
update public.wellness_practices set detail = '쌓이기 전에 현실적인 상황을 전달합니다.' where id = 'WORK-TALK-L2-01';
update public.wellness_practices set detail = '일방적이지 않은 소통 구조를 만들어갑니다.' where id = 'WORK-TALK-L2-02';
update public.wellness_practices set detail = '업무 외 대화로 협업의 기반을 다집니다.' where id = 'WORK-TALK-L2-03';
update public.wellness_practices set detail = '불편한 대화도 적절한 시점에 시도합니다.' where id = 'WORK-TALK-L2-04';
update public.wellness_practices set detail = '고립되지 않도록 주기적인 소통 자리를 갖습니다.' where id = 'WORK-TALK-L2-05';
update public.wellness_practices set detail = '퇴근 후 연락 등에 대한 나만의 원칙을 명확히 합니다.' where id = 'WORK-TALK-L3-01';
update public.wellness_practices set detail = '받는 것뿐 아니라 주는 방식도 성숙하게 다듬습니다.' where id = 'WORK-TALK-L3-02';
update public.wellness_practices set detail = '장기적으로 의지할 수 있는 동료 관계를 만듭니다.' where id = 'WORK-TALK-L3-03';
update public.wellness_practices set detail = '업무량, 역할 등을 조율하는 대화 기술을 발전시킵니다.' where id = 'WORK-TALK-L3-04';
update public.wellness_practices set detail = '원하는 방향을 주변에 알려 지원을 얻습니다.' where id = 'WORK-TALK-L3-05';
update public.wellness_practices set detail = '업무와 개인 시간의 경계를 짧게라도 지켜봅니다.' where id = 'WORK-CARE-L1-01';
update public.wellness_practices set detail = '3일 정도의 짧은 휴식이라도 미리 계획해둡니다.' where id = 'WORK-CARE-L1-02';
update public.wellness_practices set detail = '책상에서 벗어나 제대로 된 휴식을 취합니다.' where id = 'WORK-CARE-L1-03';
update public.wellness_practices set detail = '업무 모드에서 벗어나는 전환 의식을 만듭니다.' where id = 'WORK-CARE-L1-04';
update public.wellness_practices set detail = '10분이라도 온전히 쉬는 시간을 챙깁니다.' where id = 'WORK-CARE-L1-05';
update public.wellness_practices set detail = '주말 중 업무 생각을 하지 않는 시간을 확보합니다.' where id = 'WORK-CARE-L2-01';
update public.wellness_practices set detail = '일과 무관한 활동으로 에너지를 재충전합니다.' where id = 'WORK-CARE-L2-02';
update public.wellness_practices set detail = '모든 요청을 다 받아들이지 않는 연습을 합니다.' where id = 'WORK-CARE-L2-03';
update public.wellness_practices set detail = '몸과 마음의 신호를 자주 체크합니다.' where id = 'WORK-CARE-L2-04';
update public.wellness_practices set detail = '바쁜 시기 뒤에는 의식적으로 회복 시간을 배치합니다.' where id = 'WORK-CARE-L2-05';
update public.wellness_practices set detail = '소진되기 전에 휴식을 미리 배치하는 습관을 들입니다.' where id = 'WORK-CARE-L3-01';
update public.wellness_practices set detail = '일이 삶의 전부가 되지 않도록 다른 영역을 함께 키웁니다.' where id = 'WORK-CARE-L3-02';
update public.wellness_practices set detail = '단기 성과보다 오래 일할 수 있는 방식을 우선합니다.' where id = 'WORK-CARE-L3-03';
update public.wellness_practices set detail = '삶의 단계에 따라 균형의 기준을 계속 조정합니다.' where id = 'WORK-CARE-L3-04';
update public.wellness_practices set detail = '번아웃 예방이 곧 커리어 관리라는 관점을 내재화합니다.' where id = 'WORK-CARE-L3-05';
update public.wellness_practices set detail = '혼자 끌어안지 않고 가볍게 이야기해봅니다.' where id = 'WORK-HELP-L1-01';
update public.wellness_practices set detail = '비슷한 고민을 가진 사람들의 이야기를 참고합니다.' where id = 'WORK-HELP-L1-02';
update public.wellness_practices set detail = '상담, 복지 등 활용 가능한 제도를 찾아봅니다.' where id = 'WORK-HELP-L1-03';
update public.wellness_practices set detail = '가벼운 아티클이나 영상으로 관점을 넓혀봅니다.' where id = 'WORK-HELP-L1-04';
update public.wellness_practices set detail = '경험자의 시각을 가볍게 들어봅니다.' where id = 'WORK-HELP-L1-05';
update public.wellness_practices set detail = '구조적인 도움을 받을 수 있는 채널을 찾아봅니다.' where id = 'WORK-HELP-L2-01';
update public.wellness_practices set detail = '비슷한 고민을 나누는 관계를 정기적으로 만듭니다.' where id = 'WORK-HELP-L2-02';
update public.wellness_practices set detail = '믿을 만한 사람에게 주기적으로 피드백을 구합니다.' where id = 'WORK-HELP-L2-03';
update public.wellness_practices set detail = '제공되는 자원을 적극적으로 이용해봅니다.' where id = 'WORK-HELP-L2-04';
update public.wellness_practices set detail = '심해지기 전에 주변이나 상사에게 상황을 공유합니다.' where id = 'WORK-HELP-L2-05';
update public.wellness_practices set detail = '필요하다면 전문가와 함께, 또는 구조적 변화를 고려합니다.' where id = 'WORK-HELP-L3-01';
update public.wellness_practices set detail = '현재 환경이 맞지 않다면 장기적 대안을 검토합니다.' where id = 'WORK-HELP-L3-02';
update public.wellness_practices set detail = '번아웃을 예방하는 커리어 로드맵을 그려봅니다.' where id = 'WORK-HELP-L3-03';
update public.wellness_practices set detail = '코칭, 상담을 특별한 일이 아닌 자연스러운 도구로 여깁니다.' where id = 'WORK-HELP-L3-04';
update public.wellness_practices set detail = '동료, 멘토, 전문가 등 여러 층의 지원체계를 마련합니다.' where id = 'WORK-HELP-L3-05';
update public.wellness_practices set detail = '가까운 거리라도 함께 걸으며 바람을 쐽니다.' where id = 'PARENT-BODY-L1-01';
update public.wellness_practices set detail = '아이를 맡기고 5~10분만이라도 혼자 걸어봅니다.' where id = 'PARENT-BODY-L1-02';
update public.wellness_practices set detail = '짧은 틈을 이용해 몸을 풀어줍니다.' where id = 'PARENT-BODY-L1-03';
update public.wellness_practices set detail = '멀리 나가지 않아도 되는 가벼운 환기 방법입니다.' where id = 'PARENT-BODY-L1-04';
update public.wellness_practices set detail = '함께 움직이는 놀이로 스트레스를 풀어봅니다.' where id = 'PARENT-BODY-L1-05';
update public.wellness_practices set detail = '짧더라도 정기적인 운동 시간을 정해둡니다.' where id = 'PARENT-BODY-L2-01';
update public.wellness_practices set detail = '주말마다 밖에서 몸을 움직이는 시간을 늘립니다.' where id = 'PARENT-BODY-L2-02';
update public.wellness_practices set detail = '서로 돌아가며 혼자만의 시간을 확보합니다.' where id = 'PARENT-BODY-L2-03';
update public.wellness_practices set detail = '아이를 돌보는 틈틈이 몸을 챙깁니다.' where id = 'PARENT-BODY-L2-04';
update public.wellness_practices set detail = '비슷한 처지의 사람과 함께하면 지속하기 쉽습니다.' where id = 'PARENT-BODY-L2-05';
update public.wellness_practices set detail = '홈트레이닝 등 상황에 맞는 방식을 찾아 지속합니다.' where id = 'PARENT-BODY-L3-01';
update public.wellness_practices set detail = '운동을 가족 전체의 루틴으로 자리잡게 합니다.' where id = 'PARENT-BODY-L3-02';
update public.wellness_practices set detail = '부모의 체력이 곧 육아의 지속가능성임을 받아들입니다.' where id = 'PARENT-BODY-L3-03';
update public.wellness_practices set detail = '장기적으로 함께 할 활동을 미리 계획해둡니다.' where id = 'PARENT-BODY-L3-04';
update public.wellness_practices set detail = '아이 성장 단계에 맞춰 활동을 조정해갑니다.' where id = 'PARENT-BODY-L3-05';
update public.wellness_practices set detail = '오늘 하루 충분히 애썼다고 스스로에게 말해줍니다.' where id = 'PARENT-MIND-L1-01';
update public.wellness_practices set detail = '지금의 어려움이 영원하지 않음을 상기합니다.' where id = 'PARENT-MIND-L1-02';
update public.wellness_practices set detail = '반응하기 전에 아이의 입장을 잠깐 헤아려봅니다.' where id = 'PARENT-MIND-L1-03';
update public.wellness_practices set detail = '완벽하지 않아도 잘 해낸 순간을 알아챕니다.' where id = 'PARENT-MIND-L1-04';
update public.wellness_practices set detail = '자책 대신 지금의 감정을 그대로 인정합니다.' where id = 'PARENT-MIND-L1-05';
update public.wellness_practices set detail = '매일 작은 순간을 기록하며 자신감을 쌓습니다.' where id = 'PARENT-MIND-L2-01';
update public.wellness_practices set detail = '다른 집 아이·부모와의 비교를 의식적으로 줄입니다.' where id = 'PARENT-MIND-L2-02';
update public.wellness_practices set detail = '힘든 순간도 성장의 과정으로 바라보는 연습을 합니다.' where id = 'PARENT-MIND-L2-03';
update public.wellness_practices set detail = '"아이가 문제다"가 아니라 "지금 이 상황이 힘들다"로 바꿔봅니다.' where id = 'PARENT-MIND-L2-04';
update public.wellness_practices set detail = '일주일에 한 번 스스로의 상태를 돌아봅니다.' where id = 'PARENT-MIND-L2-05';
update public.wellness_practices set detail = '힘든 날일수록 스스로에게 너그러운 태도를 연습합니다.' where id = 'PARENT-MIND-L3-01';
update public.wellness_practices set detail = '아이만이 아니라 나도 함께 자라고 있음을 받아들입니다.' where id = 'PARENT-MIND-L3-02';
update public.wellness_practices set detail = '심리학의 "good enough parent" 개념을 삶에 적용합니다.' where id = 'PARENT-MIND-L3-03';
update public.wellness_practices set detail = '휘둘리지 않는 나만의 육아 기준을 세워갑니다.' where id = 'PARENT-MIND-L3-04';
update public.wellness_practices set detail = '위기의 순간마다 기댈 수 있는 생각의 틀을 만듭니다.' where id = 'PARENT-MIND-L3-05';
update public.wellness_practices set detail = '하루의 고됨을 혼자 삭히지 않고 나눠봅니다.' where id = 'PARENT-TALK-L1-01';
update public.wellness_practices set detail = '짧은 대화로 아이의 하루도 함께 들여다봅니다.' where id = 'PARENT-TALK-L1-02';
update public.wellness_practices set detail = '참지 않고 그때그때 필요한 도움을 요청합니다.' where id = 'PARENT-TALK-L1-03';
update public.wellness_practices set detail = '함께 하는 육아에 대한 인정을 표현합니다.' where id = 'PARENT-TALK-L1-04';
update public.wellness_practices set detail = '"엄마가 지금 좀 힘들어"처럼 솔직하게 표현해봅니다.' where id = 'PARENT-TALK-L1-05';
update public.wellness_practices set detail = '쌓이기 전에 주기적으로 역할을 맞춰봅니다.' where id = 'PARENT-TALK-L2-01';
update public.wellness_practices set detail = '다른 관점을 가진 부분을 정기적으로 조율합니다.' where id = 'PARENT-TALK-L2-02';
update public.wellness_practices set detail = '비슷한 상황의 사람들과 정기적으로 소통합니다.' where id = 'PARENT-TALK-L2-03';
update public.wellness_practices set detail = '성장 단계에 맞춰 대화법을 조정해갑니다.' where id = 'PARENT-TALK-L2-04';
update public.wellness_practices set detail = '역할과 어려움을 정기적으로 점검하는 자리를 갖습니다.' where id = 'PARENT-TALK-L2-05';
update public.wellness_practices set detail = '장기적으로 의지할 수 있는 관계망을 유지합니다.' where id = 'PARENT-TALK-L3-01';
update public.wellness_practices set detail = '역할 분담을 넘어 함께하는 동반자 관계로 발전시킵니다.' where id = 'PARENT-TALK-L3-02';
update public.wellness_practices set detail = '아이가 자라며 관계의 방식도 함께 변화시켜갑니다.' where id = 'PARENT-TALK-L3-03';
update public.wellness_practices set detail = '우리 가족만의 대화 방식과 전통을 만들어갑니다.' where id = 'PARENT-TALK-L3-04';
update public.wellness_practices set detail = '가까운 가족 단위를 넘어 더 넓은 지지체계를 구축합니다.' where id = 'PARENT-TALK-L3-05';
update public.wellness_practices set detail = '짧더라도 방해받지 않는 시간을 확보합니다.' where id = 'PARENT-CARE-L1-01';
update public.wellness_practices set detail = '서두르지 않고 나만의 순간을 잠깐 갖습니다.' where id = 'PARENT-CARE-L1-02';
update public.wellness_practices set detail = '감정이 격해질 때 잠시 멈추는 연습을 합니다.' where id = 'PARENT-CARE-L1-03';
update public.wellness_practices set detail = '언제가 가장 버거운지 알면 대비할 수 있습니다.' where id = 'PARENT-CARE-L1-04';
update public.wellness_practices set detail = '오늘 하루를 버틴 것에 대한 작은 위로를 챙깁니다.' where id = 'PARENT-CARE-L1-05';
update public.wellness_practices set detail = '혼자 다 하려 하지 않고 자원을 적극 활용합니다.' where id = 'PARENT-CARE-L2-01';
update public.wellness_practices set detail = '서로의 휴식 시간을 규칙적으로 보장해줍니다.' where id = 'PARENT-CARE-L2-02';
update public.wellness_practices set detail = '육아 사이에도 나를 위한 시간을 계획해 넣습니다.' where id = 'PARENT-CARE-L2-03';
update public.wellness_practices set detail = '짧은 낮잠 등 회복 방법을 꾸준히 활용합니다.' where id = 'PARENT-CARE-L2-04';
update public.wellness_practices set detail = '번아웃 신호를 놓치지 않고 자주 체크합니다.' where id = 'PARENT-CARE-L2-05';
update public.wellness_practices set detail = '일시적이 아닌 지속 가능한 형태로 자리잡게 합니다.' where id = 'PARENT-CARE-L3-01';
update public.wellness_practices set detail = '부모 역할 외의 나 자신도 계속 가꿔갑니다.' where id = 'PARENT-CARE-L3-02';
update public.wellness_practices set detail = '혼자 감당하지 않는 구조를 미리 만들어둡니다.' where id = 'PARENT-CARE-L3-03';
update public.wellness_practices set detail = '나를 돌보는 것이 아이에게도 좋다는 것을 체득합니다.' where id = 'PARENT-CARE-L3-04';
update public.wellness_practices set detail = '아이가 자라며 나를 돌보는 방법도 함께 바꿔갑니다.' where id = 'PARENT-CARE-L3-05';
update public.wellness_practices set detail = '비슷한 고민을 가진 사람들과 가볍게 이야기해봅니다.' where id = 'PARENT-HELP-L1-01';
update public.wellness_practices set detail = '믿을 만한 자료로 지금의 상황을 이해해봅니다.' where id = 'PARENT-HELP-L1-02';
update public.wellness_practices set detail = '짧은 시간이라도 부탁해보는 것부터 시작합니다.' where id = 'PARENT-HELP-L1-03';
update public.wellness_practices set detail = '막연한 답답함을 글로 정리하며 상태를 파악합니다.' where id = 'PARENT-HELP-L1-04';
update public.wellness_practices set detail = '활용 가능한 공공 자원을 확인해봅니다.' where id = 'PARENT-HELP-L1-05';
update public.wellness_practices set detail = '체계적인 자료와 모임을 꾸준히 활용합니다.' where id = 'PARENT-HELP-L2-01';
update public.wellness_practices set detail = '일회성이 아닌 지속적인 도움 체계를 마련합니다.' where id = 'PARENT-HELP-L2-02';
update public.wellness_practices set detail = '필요할 때마다 전문가의 의견을 구합니다.' where id = 'PARENT-HELP-L2-03';
update public.wellness_practices set detail = '지속적인 관계 속에서 정보와 지지를 나눕니다.' where id = 'PARENT-HELP-L2-04';
update public.wellness_practices set detail = '혼자 참기보다 자주 도움을 요청하는 것을 연습합니다.' where id = 'PARENT-HELP-L2-05';
update public.wellness_practices set detail = '개인 상담이나 부모교육을 통해 전문적 도움을 받아봅니다.' where id = 'PARENT-HELP-L3-01';
update public.wellness_practices set detail = '가족, 이웃, 전문가로 이어지는 다층적 지지체계를 만듭니다.' where id = 'PARENT-HELP-L3-02';
update public.wellness_practices set detail = '완벽히 혼자 해내야 한다는 부담을 내려놓습니다.' where id = 'PARENT-HELP-L3-03';
update public.wellness_practices set detail = '발달 단계별로 필요한 도움을 미리 알아둡니다.' where id = 'PARENT-HELP-L3-04';
update public.wellness_practices set detail = '일반적인 조언보다 우리 가족에게 맞는 방식을 함께 찾습니다.' where id = 'PARENT-HELP-L3-05';

commit;
